modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="amethystia"
version="1.0.0"
displayName="Amethystia"
credits="Mod for u"
displayURL="https://discord.gg/NTtMzrbZ"
authors="EUGENE, Hnufelka"

[[dependencies.amethystia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.amethystia]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.amethystia]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

